version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vulnrag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/vulnrag
      APP_NAME: VulnRAG API
    command:
      sh -c "pip install -r requirements.txt && uvicorn app.main:app --host
      0.0.0.0 --port 8000"
    ports:
      - '8000:8000'

volumes:
  postgres_data:
  pgadmin_data:
